export const CHAT_ADDITION_STARTED = 'CHAT_ADDITION_STARTED'
export const CHAT_ADDITION_COMPLETED = 'CHAT_ADDITION_COMPLETED'
export const CHAT_ADDITION_FAILED = 'CHAT_ADDITION_FAILED'

export const CHATS_FETCHING_STARTED = 'CHATS_FETCHING_STARTED'
export const CHATS_FETCHING_COMPLETED = 'CHATS_FETCHING_COMPLETED'
export const CHATS_FETCHING_FAILED = 'CHATS_FETCHING_FAILED'

export const USER_ADDITION_STARTED = 'USER_ADDITION_STARTED'
export const USER_ADDITION_COMPLETED = 'USER_ADDITION_COMPLETED'
export const USER_ADDITION_FAILED = 'USER_ADDITION_FAILED'

export const ADMIN_ADDITION_STARTED = 'ADMIN_ADDITION_STARTED'
export const ADMIN_ADDITION_COMPLETED = 'ADMIN_ADDITION_COMPLETED'
export const ADMIN_ADDITION_FAILED = 'ADMIN_ADDITION_FAILED'

export const CHAT_SELECTED = 'CHAT_SELECTED'