export const COMMENT_ADDITION_STARTED = 'COMMENT_ADDITION_STARTED'
export const COMMENT_ADDITION_COMPLETED = 'COMMENT_ADDITION_COMPLETED'
export const COMMENT_ADDITION_FAILED = 'COMMENT_ADDITION_FAILED'

export const COMMENTS_FETCHING_STARTED = 'COMMENTS_FETCHING_STARTED'
export const COMMENTS_FETCHING_COMPLETED = 'COMMENTS_FETCHING_COMPLETED'
export const COMMENTS_FETCHING_FAILED = 'COMMENTS_FETCHING_FAILED'