export const CURRENT_POST_FETCH_STARTED = 'CURRENT_POST_FETCH_STARTED'
export const CURRENT_POST_FETCH_COMPLETED = 'CURRENT_POST_FETCH_COMPLETED'
export const CURRENT_POST_FETCH_FAILED = 'CURRENT_POST_FETCH_FAILED'
export const CURRENT_POST_SELECTEDD = 'CURRENT_POST_SELECTED'