export const POST_FETCH_STARTED = 'POST_FETCH_STARTED';
export const POST_FETCH_COMPLETED = 'POST_FETCH_COMPLETED';
export const POST_FETCH_FAILEED = 'POST_FETCH_FAILED';

export const USER_POSTS_STARTED = 'USER_POSTS_STARTED'
export const USER_POSTS_COMPLETED = 'USER_POSTS_COMPLETED'
export const USER_POSTS_FAILED = 'USER_POSTS_FAILED'

export const POSTS_SETTED_TO_NULL = 'POSTS_SETTED_TO_NULL'