export const PICTURE_SETTED = 'PICTURE_SETTED';

export const POST_ADDED_STARTED = 'POST_ADDED_STARTED';
export const POST_ADDED_COMPLETED = 'POST_ADDED_COMPLETED';
export const POST_ADDED_FAILED = 'POST_ADDED_FAILED';