export const VERSUS_LIKE_STARTED = 'VERSUS_LIKE_STARTED'
export const VERSUS_LIKE_COMPLETED = 'VERSUS_LIKE_COMPLETED'
export const VERSUS_LIKE_FAILED = 'VERSUS_LIKE_FAILED'

export const VERSUS_HEART_STARTED = 'VERSUS_HEART_STARTED'
export const VERSUS_HEART_COMPLETED = 'VERSUS_HEART_COMPLETED'
export const VERSUS_HEART_FAILED = 'VERSUS_HEART_FAILED'

export const VERSUS_UNLIKE_STARTED = 'VERSUS_UNLIKE_STARTED'
export const VERSUS_UNLIKE_COMPLETED = 'VERSUS_UNLIKE_COMPLETED'
export const VERSUS_UNLIKE_FAILED = 'VERSUS_UNLIKE_FAILED'

export const VERSUS_UNHEART_STARTED = 'VERSUS_UNHEART_STARTED'
export const VERSUS_UNHEART_COMPLETED = 'VERSUS_UNHEART_COMPLETED'
export const VERSUS_UNHEART_FAILED = 'VERSUS_UNHEART_FAILED'

export const VERSUS_LIKE_FETCH_STARTED = 'VERSUS_LIKE_FETCH_STARTED'
export const VERSUS_LIKE_FETCH_COMPLETED = 'VERSUS_LIKE_FETCH_COMPLETED'
export const VERSUS_LIKE_FETCH_FAILED = 'VERSUS_LIKE_FETCH_FAILED'

export const VERSUS_HEART_FETCH_STARTED = 'VERSUS_HEART_FETCH_STARTED'
export const VERSUS_HEART_FETCH_COMPLETED = 'VERSUS_HEART_FETCH_COMPLETED'
export const VERSUS_HEART_FETCH_FAILED = 'VERSUS_HERAT_FETCH_FAILED'