export const REPORT = 'REPORT';

export const SEND_REPORT_STARTED = 'SEND_REPORT_STARTED';
export const SEND_REPORT_COMPLETED = 'SEND_REPORT_COMPLETED';
export const SEND_REPORT_FAILED = 'SEND_REPORT_FAILED';