export const STORIES_HIDDEN = 'STORIES_HIDDEN'
export const STORIES_SHOWED = 'STORIES_SHOWED'

export const STORIES_FETCHING_STARTED = 'STORIES_FETCHING_STARTED'
export const STORIES_FETCHING_COMPLETED = 'STORIES_FETCHING_COMPLETED'
export const STORIES_FETCHING_FAILED = 'STORIES_FETCHING_FAILED'

export const STORY_SELECTED = 'STORY_SELECTED'