export const TOPIC_FETCH_STARTED = 'TOPIC_FETCH_STARTED';
export const TOPIC_FETCH_COMPLETED = 'TOPIC_FETCH_COMPLETED';
export const TOPIC_FETCH_FAILED = 'TOPIC_FETCH_FAILED';

export const TOPIC_SELECTED = 'TOPIC_SELECTED'