export const TOPIC_FETCH_STARTED = 'TOPIC_FETCH_STARTED';
export const TOPIC_FETCH_COMPLETED = 'TOPIC_FETCH_COMPLETED';
export const TOPIC_FETCH_FAILED = 'TOPIC_FETCH_FAILED';

export const TOPIC_STARTED = 'TOPIC_STARTED';
export const TOPIC_COMPLETED = 'TOPIC_COMPLETED';
export const TOPIC_FAILED = 'TOPIC_FAILED';

export const TOPIC_SELECTED = 'TOPIC_SELECTED'

export const TOPIC_ADDITION_STARTED = 'TOPIC_ADDITION_STARTED'
export const TOPIC_ADDITION_COMPLETED = 'TOPIC_ADDITION_COMPLETED'
export const TOPIC_ADDITION_FAILED = 'TOPIC_ADDITION_FAILED'