export const USER_FOLLOW_STARTED = 'USER_FOLLOW_STARTED'
export const USER_FOLLOW_COMPLETED = 'USER_FOLLOW_COMPLETED'
export const USER_FOLLOW_FAILED = 'USER_FOLLOW_FAILED'

export const USER_UNFOLLOW_STARTED = 'USER_UNFOLLOW_STARTED'
export const USER_UNFOLLOW_COMPLETED = 'USER_UNFOLLOW_COMPLETED'
export const USER_UNFOLLOW_FAILED = 'USER_UNFOLLOW_FAILED'

export const USER_IS_FOLLOWING_FETCH_STARTED = 'USER_IS_FOLLOWING_FETCH_STARTED'
export const USER_IS_FOLLOWING_FETCH_COMPLETED = 'USER_IS_FOLLOWING_FETCH_COMPLETED'
export const USER_IS_FOLLOWING_FETCH_FAILED = 'USER_IS_FOLLOWING_FETCH_FAILED'

export const EXTRA_USER_FOLLOW_STARTED = 'EXTRA_USER_FOLLOW_STARTED'
export const EXTRA_USER_FOLLOW_COMPLETED = 'EXTRA_USER_FOLLOW_COMPLETED'
export const EXTRA_USER_FOLLOW_FAILED = 'EXTRA_USER_FOLLOW_FAILED'

export const EXTRA_USER_UNFOLLOW_STARTED = 'EXTRA_USER_UNFOLLOW_STARTED'
export const EXTRA_USER_UNFOLLOW_COMPLETED = 'EXTRA_USER_UNFOLLOW_COMPLETED'
export const EXTRA_USER_UNFOLLOW_FAILED = 'EXTRA_USER_UNFOLLOW_FAILED'

export const EXTRA_USER_IS_FOLLOWING_FETCH_STARTED = 'EXTRA_USER_IS_FOLLOWING_FETCH_STARTED'
export const EXTRA_USER_IS_FOLLOWING_FETCH_COMPLETED = 'EXTRA_USER_IS_FOLLOWING_FETCH_COMPLETED'
export const EXTRA_USER_IS_FOLLOWING_FETCH_FAILED = 'USER_IS_FOLLOWING_FETCH_FAILED'

export const USER_SETTED = 'USER_SETTED'
export const EXTRA_USER_SETTED = 'EXTRA_USER_SETTED' 

export const FOLLOWING_FETCH_STARTED = 'FOLLOWING_FETCH_STARTED'
export const FOLLOWING_FETCH_COMPLETED = 'FOLLOWING FETCH COMPLETED'
export const FOLLOWING_FETCH_FAILED = 'FOLLOWING_FETCH_FAILED'

export const FOLLOWERS_FETCH_STARTED = 'FOLLOWERS_FETCH_STARTED'
export const FOLLOWERS_FETCH_COMPLETED = 'FOLLOWERS FETCH_COMPLETED'
export const FOLLOWERS_FETCH_FAILED = 'FOLLOWERS_FETCH_FAILED'

export const UPDATE_STARTED = 'UPDATE_STARTED'
export const UPDATE_COMPLETED = 'UPDATE_COMPLETED'
export const UPDATE_FAILED = 'UPDATE_FAILED'

export const DELETE_STARTED = 'DELETE_STARTED'
export const DELETE_COMPLETED = 'DELETE_COMPLETED'
export const DELETE_FAILED = 'DELETE_FAILED'

export const USER_STORIES_STARTED = 'USER_STORIES_STARTED'
export const USER_STORIES_COMPLETED = 'USER_STORIES_COMPLETED'
export const USER_STORIES_FAILED = 'USER_STORIES_FAILED'


export const USER_STARTED = 'USER_STARTED'
export const USER_COMPLETED = 'USER_COMPLETED'
export const USER_FAILED = 'USER_FAILED'

export const PROFILE_EDITED = 'PROFILE_EDITED'

export const NULL_SETTED = 'NULL_SETTED'