export const USER_FOLLOW_STARTED = 'USER_FOLLOW_STARTED'
export const USER_FOLLOW_COMPLETED = 'USER_FOLLOW_COMPLETED'
export const USER_FOLLOW_FAILED = 'USER_FOLLOW_FAILED'

export const USER_UNFOLLOW_STARTED = 'USER_UNFOLLOW_STARTED'
export const USER_UNFOLLOW_COMPLETED = 'USER_UNFOLLOW_COMPLETED'
export const USER_UNFOLLOW_FAILED = 'USER_UNFOLLOW_FAILED'

export const USER_IS_FOLLOWING_FETCH_STARTED = 'USER_IS_FOLLOWING_FETCH_STARTED'
export const USER_IS_FOLLOWING_FETCH_COMPLETED = 'USER_IS_FOLLOWING_FETCH_COMPLETED'
export const USER_IS_FOLLOWING_FETCH_FAILED = 'USER_IS_FOLLOWING_FETCH_FAILED'

export const EXTRA_USER_FOLLOW_STARTED = 'EXTRA_USER_FOLLOW_STARTED'
export const EXTRA_USER_FOLLOW_COMPLETED = 'EXTRA_USER_FOLLOW_COMPLETED'
export const EXTRA_USER_FOLLOW_FAILED = 'EXTRA_USER_FOLLOW_FAILED'

export const EXTRA_USER_UNFOLLOW_STARTED = 'EXTRA_USER_UNFOLLOW_STARTED'
export const EXTRA_USER_UNFOLLOW_COMPLETED = 'EXTRA_USER_UNFOLLOW_COMPLETED'
export const EXTRA_USER_UNFOLLOW_FAILED = 'EXTRA_USER_UNFOLLOW_FAILED'

export const EXTRA_USER_IS_FOLLOWING_FETCH_STARTED = 'EXTRA_USER_IS_FOLLOWING_FETCH_STARTED'
export const EXTRA_USER_IS_FOLLOWING_FETCH_COMPLETED = 'EXTRA_USER_IS_FOLLOWING_FETCH_COMPLETED'
export const EXTRA_USER_IS_FOLLOWING_FETCH_FAILED = 'USER_IS_FOLLOWING_FETCH_FAILED'

export const USER_SETTED = 'USER_SETTED'
export const EXTRA_USER_SETTED = 'EXTRA_USER_SETTED' 