export const VERSUS_VOTE_STARTED = 'VERSUS_VOTE_STARTED'
export const VERSUS_VOTE_COMPLETED = 'VERSUS_VOTE_COMPLETED'
export const VERSUS_VOTE_FAILED = 'VERSUS_VOTE_FAILED'

export const VERSUS_SHARE_STARTED = 'VERSUS_SHARE_STARTED'
export const VERSUS_SHARE_COMPLETED = 'VERSUS_SHARE_COMPLETED'
export const VERSUS_SHARE_FAILED = 'VERSUS_SHARE_FAILED'

export const VERSUS_FETCHING_STARTED = 'VERSUS_FETCHING_STARTED'
export const VERSUS_FETCHING_COMPLETED = 'VERSUS_FETCHING_COMPLETED'
export const VERSUS_FETCHING_FAILED = 'VERSUS_FETCHING_FAILED'

export const setNull = "SET_NULL"